### ISSUE TITLE
Broken functionality

### ISSUE THREAD

**Issue by pryrt** [rainman74/NPPTextFX2#2] opened 2022-07-16 16:18 UTC
Many of the TextFX Characters (including Swap Quotes, Escape , Unescape , and Case converts (non-exhaustive list)) drop the final character of the selection when it replaces.

This is due to the change in Scintilla 5.1.5, described [here](https://www.scintilla.org/ScintillaHistory.html#:~:text=When%20calling%20SCI_GETTEXT,with%20other%20APIs), which means that every call in your plugin to SCI_GETTEXT, SCI_GETSELTEXT, and SCI_GETCURLINE will have to be fixed, because they will be off-by-one-byte compared to the existing code.

**Comment by pryrt** [comment] 2022-07-16 20:08
see the details in @rpidaro's post [here](https://github.com/rainman74/NPPTextFX2/issues/2)

**Comment by rainman74** [comment] 2022-07-17 13:46
> Many of the TextFX Characters (including Swap Quotes, Escape , Unescape , and Case converts (non-exhaustive list)) drop the final character of the selection when it replaces.
> 
> This is due to the change in Scintilla 5.1.5, described [here](https://www.scintilla.org/ScintillaHistory.html#:~:text=When%20calling%20SCI_GETTEXT,with%20other%20APIs), which means that every call in your plugin to SCI_GETTEXT, SCI_GETSELTEXT, and SCI_GETCURLINE will have to be fixed, because they will be off-by-one-byte compared to the existing code.

I'll take a look...

**Comment by rainman74** [comment] 2022-07-17 13:46
> see the details in @rpidaro's post [here](https://github.com/rainman74/NPPTextFX2/issues/2)

Wrong link?!

**Comment by pryrt** [comment] 2022-07-17 14:15
https://community.notepad-plus-plus.org/post/78446

**Comment by rainman74** [comment] 2022-07-17 14:45
> Many of the TextFX Characters (including Swap Quotes, Escape , Unescape , and Case converts (non-exhaustive list)) drop the final character of the selection when it replaces.

The problem is fixed with the 1.0 release. All functions should now be compatible again with the current Notepad++ and Scintilla 5.1.5+, hence the version upgrade to 1.0.

**Closed** 2022-07-17 14:45 UTC
